# Select image from https://hub.docker.com/r/_/php/
image: php:7.0

# Services
services:
  - mysql:latest

# Variables and root user used
variables:
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: gitlab-ci
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: your_db_name

# Before Script
before_script:
  - php -v

test:app:
  script:
    - phpunit -c app --debug