<?php

namespace AppBundle\Repository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeOldPhotos()
    {
        $qb = $this->createQueryBuilder('entity');

        $oldPhotoDay = new \DateTime("+7 days");
        $oldPhotoDay = $oldPhotoDay->format('Y-m-d h:m:i');

        $oldPhotosCount = $qb->select('count(entity.id)')->where($qb->expr()->eq('entity.isUsed', 0))
            ->andWhere($qb->expr()->lte('entity.creationDate', $qb->expr()->literal($oldPhotoDay)))
            ->getQuery()->getSingleScalarResult();

        $qb->delete('AppBundle:Photo', 'entity')
            ->where($qb->expr()->eq('entity.isUsed', 0))
            ->andWhere($qb->expr()->lte('entity.creationDate', $qb->expr()->literal($oldPhotoDay)))
            ->getQuery()->execute();

        return $oldPhotosCount;
    }
}
