<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCreatedTodayProductCount(User $user)
    {
        $queryBuilder = $this->createQueryBuilder('entity');
        try {
            $result = $queryBuilder->select('COUNT(entity)')
                ->where('entity.creationDate >= CURRENT_DATE()')
                ->andWhere('entity.user = :userId')
                ->setParameter('userId', $user->getId())
                ->getQuery()->getSingleScalarResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }

        return intval($result);
    }
}
