<?php

namespace Vidia\AuthBundle\Repository;

use Vidia\AuthBundle\Entity\UserInterface;

/**
 * SessionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function killCurrent(UserInterface $user, $token)
    {
        $query = $this->createQueryBuilder('entity')
            ->delete('VidiaAuthBundle:Session', 'entity')
            ->where('entity.accessToken = :token')
            ->andWhere('entity.user = :user')
            ->setParameters(['token' => $token, 'user' => $user]);

        try {
            $query->getQuery()->getResult();
        } catch (\Exception $exception) {
            return false;
        }
    }

    public function killAllExceptCurrent(UserInterface $user, $token)
    {
        $query = $this->createQueryBuilder('entity')
            ->delete('VidiaAuthBundle:Session', 'entity')
            ->where('entity.accessToken != :token')
            ->andWhere('entity.user = :user')
            ->setParameters(['token' => $token, 'user' => $user]);

        try {
            $query->getQuery()->getResult();
        } catch (\Exception $exception) {
            return false;
        }
    }
}
