<?php

namespace Vidia\AuthBundle\Repository;

use Vidia\AuthBundle\Entity\UserInterface;

/**
 * SessionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function killCurrent(UserInterface $user, $token)
    {
        $query = $this->createQueryBuilder('entity')
            ->delete('VidiaAuthBundle:Session', 'entity')
            ->where('entity.accessToken = :token')
            ->andWhere('entity.user = :user')
            ->setParameters(['token' => $token, 'user' => $user]);

        try {
            $query->getQuery()->getResult();
        } catch (\Exception $exception) {
            return false;
        }
    }

    public function killAllExceptCurrent(UserInterface $user, $token)
    {
        $query = $this->createQueryBuilder('entity')
            ->delete('VidiaAuthBundle:Session', 'entity')
            ->where('entity.accessToken != :token')
            ->andWhere('entity.user = :user')
            ->setParameters(['token' => $token, 'user' => $user]);

        try {
            $query->getQuery()->getResult();
        } catch (\Exception $exception) {
            return false;
        }
    }

    public function getLastDateOnlineByUserId($userId)
    {
        $qb = $this->createQueryBuilder('entity');
        $query = $qb->select('entity.online')
            ->where('entity.user = :userId')
            ->orderBy('entity.online', 'DESC')
            ->setMaxResults(1)
            ->setParameter('userId', $userId);
        try {
            return $query->getQuery()->getSingleScalarResult();
        } catch (\Exception $exception) {
            return false;
        }
    }

    public function getUsersOnlineCount()
    {
        $today = new \DateTime('- 15 minutes');

        $qb = $this->createQueryBuilder('entity');
        $query = $qb->select($qb->expr()->countDistinct('entity.user'))
            ->where($qb->expr()->gte('entity.online', $qb->expr()->literal($today->format('Y-m-d H:i:s'))));

        try {
            return $query->getQuery()->getSingleScalarResult();
        } catch (\Exception $exception) {
            return false;
        }
    }

}
